services:
  flask-server:
    env_file: ".env.example"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"