services:
  flask-server:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "8080"
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_HOST: db
   ports:
     - "8080:8080"
   depends_on:
      - db
   command: >
      sh -c "
      until pg_isready -h ${POSTGRES_HOST} -U ${POSTGRES_USER}; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      ./migrate.sh"
  db:
    image: postgres:15.4-alpine3.18
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"